name: canopy-gis-prod

services:
  server:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/canopy-gis-server-prod:latest
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    environment:
      CORS_ORIGIN: ${CORS_ORIGIN}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL}
      DATABASE_URL: ${DATABASE_URL}
    restart: always
    ports:
      - "3000:3000"

  worker:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/canopy-gis-worker-prod:latest
    build:
      context: .
      dockerfile: packages/worker/Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      BULLMQ_PORT: ${BULLMQ_PORT}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET_BASIS_LAYERS: ${AWS_S3_BUCKET_BASIS_LAYERS}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_S3_PREFIX: ${AWS_S3_PREFIX}
      AWS_S3_PUBLIC_BASE_URL: ${AWS_S3_PUBLIC_BASE_URL}
      SF_CLIENT_ID: ${SF_CLIENT_ID}
      SF_USERNAME: ${SF_USERNAME}
      SF_PRIVATE_KEY_PATH: ${SF_PRIVATE_KEY_PATH}
      SF_AUTH_URL: ${SF_AUTH_URL}
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY} 
    restart: always
    depends_on:
      - redis
    ports:
      - "${BULLMQ_PORT}:4000"

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning

volumes:
  redis_data:
